.TH CLNDRANGE_SET "3" "2009-11-10" "libstdcl-0.7" "Standard Compute Layer (CL) Manual"
.SH NAME
clndrange_set1d, clndrange_set2d, clndrange_set3d - Set the index-space (NDRange) for the execution of a CL kernel
.SH SYNOPSIS
.B #include <stdcl.h>
.sp
.BI "clndrange_set1d( clndrange_t " ndr ", " gtoff0 "," gt0 "," lt0 );
.sp
.BI "clndrange_set2d( clndrange_t " ndr ", " gtoff0 "," gt0 "," lt0 ", " gtoff1 "," gt1 "," lt1 );
.sp
.BI "clndrange_set3d( clndrange_t " ndr ", " gtoff0 "," gt0 "," lt0 ", " gtoff1 "," gt1 "," lt1 ", " gtoff2 "," gt2 "," lt2 );
.SH DESCRIPTION
clndrange_set() family of macros are used to set an object of type clndrange_t 
to define the index-space for the execution of a CL kernel.  
The values of \fIgtoff\fPn, \fIgt\fPn, \fIlt\fPn define the global index
offset, global index range and local index range, respectively, for 
dimension n.  The index-space defines the work-group and work-item
partitioning for the kernel execution.
.SH EXAMPLES
Setting a 1-D index-space of 16 work-items with work-group size of 2 and no global offset:
.sp
.in +4n
.nf
    clndrange_t ndr;
    ...
    clndrange_set1d( ndr, 0,16,2 );
.fi
.in
.PP
Setting a 2-D index-space of 64 by 128 work-items with work-group
size of 2 by 4 with a global work-item offset of 32,64:
.sp
.in +4n
.nf
    clndrange_t ndr;
    ...
    clndrange_set2d( ndr, 32,64,2, 64,128,4 );
.fi
.in
.SH AUTHOR
Written by David Richie.
.SH REPORTING BUGS
Report bugs to <support@browndeertechnology.com>
.SH COPYRIGHT
Copyright (C) 2009 Brown Deer Technology, LLC.  Licensed under the
GNU Lesser General Public License version 3 (LGPLv3).
There is NO WARRANTY to the extent permitted by law.
.SH SEE ALSO
clndrange_init(3), clfork(3), stdcl(3)
