.TH CLARG_SET "3" "2010-8-12" "libstdcl-1.0" "Standard Compute Layer (CL) Manual"
.SH NAME
clarg_set, clarg_set_global, clarg_set_local \- Set CL kernel arguments
.SH SYNOPSIS
.B #include <stdcl.h>
.sp
.BI "void clarg_set( CONTEXT* cp, cl_kernel " krn ", unsigned int " argnum ", Tn " arg );
.sp
.BI "void clarg_set_global( CONTEXT* cp, cl_kernel " krn ", unsigned int " argnum ", void* " ptr );
.sp
.BI "void clarg_set_local( CONTEXT* cp, cl_kernel " krn ", unsigned int " argnum ", size_t " sizeb );
.SH DESCRIPTION
clarg_set(), clarg_set_global() and clarg_set_local() are used to set the
\fIargnum\fP argument of the CL kernel \fIkrn\fP prior to kernel execution.
.PP
clarg_set() is used for setting arguments of intrinsic type such as cl_int,
cl_float or cl_float4, etc.  For clarg_set() Tn can be any valid scalar or
vector type.
.PP
clarg_set_global is used for setting arguments of pointers to global memory
where \fIptr\fP points to memory that was allocated using a call to clmalloc()
and attached to the CL context of the target kernel.
.PP
clarg_set_local() is used for setting arguments of pointers to local memory
where \fIsizeb\fP indicates the size in bytes of the local memory that is
to be allocated.
.SH AUTHOR
Written by David Richie.
.SH REPORTING BUGS
Report bugs to <support@browndeertechnology.com>
.SH COPYRIGHT
Copyright (C) 2009 Brown Deer Technology, LLC.  Licensed under the
GNU Lesser General Public License version 3 (LGPLv3).
There is NO WARRANTY to the extent permitted by law.
.SH SEE ALSO
clfork(3), clsym(3), clmalloc(3), stdcl(3)
