.TH CLLOAD "3" "2010-8-12" "libstdcl-1.0" "Standard Compute Layer (CL) Manual"
.SH NAME
clload \- dynamic loader for CL source and binary programs
.SH SYNOPSIS
.B #include <stdcl.h>
.sp
.BI "void* clload( CONTEXT* " cp ", void* " ptr ", size_t "  len ", int " flags );
.sp
Link with \fI\-lstdcl\fP.
.SH DESCRIPTION
The function clload() is used to dynamically load CL programs into a CL 
context, where \fIptr\fP points to the source or binary of length \fIlen\fP.
A CL program will be built (compiled) from source or binary and for all
devices within the target context.  A call to clload() returns a non-zero
value on success and zero on error.
.PP
The function clload() is normally used indirectly through the interface
provided by clopen(), clsym() and clclose().  
.SH AUTHOR
Written by David Richie.
.SH REPORTING BUGS
Report bugs to <support@browndeertechnology.com>
.SH COPYRIGHT
Copyright (C) 2009 Brown Deer Technology, LLC.  Licensed under the 
GNU Lesser General Public License version 3 (LGPLv3).  
There is NO WARRANTY to the extent permitted by law.
.SH SEE ALSO
clopen(3), clsym(3), clclose(), clld(1), stdcl(3)
