.TH CLMSYNC "3" "2011-6-13" "libstdcl-1.2" "Standard Compute Layer (CL) Manual"
.SH NAME
clmsync \- Synchronize memory between host and co-processor device
.SH SYNOPSIS
.B #include <stdcl.h>
.sp
.BI "cl_event clmsync( CONTEXT* " cp ", unsigned int " devnum ", void* " ptr ", int " flags );
.sp
Link with \fI\-lstdcl\fP.
.SH DESCRIPTION
clmsync() is used to synchronize memory between the host and a compute 
layer (CL) co-processor device.
The memory pointed to by \fIptr\fP must have been created using a call to
clmalloc() and associated with a CL context.  
.PP
The behavior of clmsync() is controlled by the flags argument which must
be set with either CL_MEM_HOST or CL_MEM_DEVICE.  These flags are mutually
exclusive and it is an error to set both or none.  The following flags may
be used:
.TP
.B CL_MEM_HOST
clmsync() will sync the memory on the host.
.TP
.B CL_MEM_DEVICE
clmsync() will sync the memory on the device.
.TP
.B CL_EVENT_WAIT
clmsync() will block until the operation has completed.
.TP
.B CL_EVENT_NOWAIT
clmsync() will return immediately.  The programmer must ensure that the
operation has completed using clwait() or clwaitev().
.TP
.B CL_EVENT_NORELEASE
Used with CL_EVENT_WAIT to prevent clfork() from releasing the CL event
generated
by the operation.  If this flag is used the programmer is responsible
for releasing the returned event using clReleaseEvent().  This flag has
no effect when CL_EVENT_NOWAIT is used.
.B CL_EVENT_RELEASE
This flag is deprecated and should no longer be used.
.SH RETURN VALUE
On error clmsync() will return (cl_event)(-1) and errno is set appropriately.
.SH AUTHOR
Written by David Richie.
.SH REPORTING BUGS
Report bugs to <support@browndeertechnology.com>
.SH COPYRIGHT
Copyright (C) 2009-2011 Brown Deer Technology, LLC.  Licensed under the
GNU Lesser General Public License version 3 (LGPLv3).
There is NO WARRANTY to the extent permitted by law.
.SH SEE ALSO
clwait(3), clwaitev(3), clmalloc(3), clfree(3), stdcl(3)
